#!/usr/bin/env python3
"""Copy root .env into Atlasbound/atlasbound.env for DEBUG bundle loading."""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / ".env"
EXAMPLE = ROOT / ".env.example"
DST = ROOT / "Atlasbound" / "atlasbound.env"


def main() -> int:
    source = SRC if SRC.exists() else EXAMPLE
    if not source.exists():
        print("No .env or .env.example found; writing empty atlasbound.env", file=sys.stderr)
        DST.write_text("# Generated by scripts/sync-env.py\n", encoding="utf-8")
        return 0
    text = source.read_text(encoding="utf-8")
    DST.write_text(
        "# Generated by scripts/sync-env.py — do not edit; change root .env instead\n" + text,
        encoding="utf-8",
    )
    print(f"Synced {source.name} → Atlasbound/atlasbound.env")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
